# permissions for end users to edit ipas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ipa
    app.kubernetes.io/managed-by: kustomize
  name: ipa-editor-role
rules:
- apiGroups:
  - ipa.shafinhasnat.me
  resources:
  - ipas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipa.shafinhasnat.me
  resources:
  - ipas/status
  verbs:
  - get
