apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: ipa.shafinhasnat.me/v1alpha1
kind: IPA
metadata:
  labels:
    app.kubernetes.io/name: ipa
    app.kubernetes.io/managed-by: kustomize
  name: ipa-sample
spec:
  ipaRules:
    - deployment: nginx-deployment
      namespace: default
      defaultReplicas: 1
      rules:
        - from: 13
          to: 16
          replicas: 4
        - from: 17
          to: 1
          replicas: 2
  # TODO(user): Add fields here

